"""remove_retell_api_secret_from_tenants_and_locations

Revision ID: 4135a8bffe53
Revises: 4ebcba46a569
Create Date: 2026-02-22 22:56:21.055595+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4135a8bffe53'
down_revision: Union[str, None] = '4ebcba46a569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_locations', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('tenant_locations', 'retell_api_secret_encrypted')
    op.drop_column('tenants', 'retell_api_secret_encrypted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('retell_api_secret_encrypted', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tenant_locations', sa.Column('retell_api_secret_encrypted', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('tenant_locations', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
