"""add contacts calls custom_fields tables

Revision ID: 4ebcba46a569
Revises: 02020a12359a
Create Date: 2026-02-22 22:06:48.968719+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ebcba46a569'
down_revision: Union[str, None] = '02020a12359a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('email_encrypted', sa.Text(), nullable=True),
    sa.Column('phone_encrypted', sa.Text(), nullable=True),
    sa.Column('date_of_birth_encrypted', sa.Text(), nullable=True),
    sa.Column('phone_hash', sa.String(length=64), nullable=True),
    sa.Column('nexhealth_patient_id', sa.String(length=128), nullable=True),
    sa.Column('chat_session_id', sa.String(length=255), nullable=True),
    sa.Column('last_agent_interaction_id', sa.String(length=255), nullable=True),
    sa.Column('is_new_patient', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'phone_hash', name='uq_contact_tenant_phone')
    )
    op.create_index('ix_contact_tenant', 'contacts', ['tenant_id'], unique=False)
    op.create_index('ix_contact_tenant_nexhealth', 'contacts', ['tenant_id', 'nexhealth_patient_id'], unique=False)
    op.create_index(op.f('ix_contacts_tenant_id'), 'contacts', ['tenant_id'], unique=False)
    op.create_table('custom_field_definitions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('dropdown_options', sa.JSON(), nullable=True),
    sa.Column('is_phi', sa.Boolean(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'entity_type', 'field_key', name='uq_custom_field_tenant_entity_key')
    )
    op.create_index('ix_custom_field_def_tenant_entity', 'custom_field_definitions', ['tenant_id', 'entity_type'], unique=False)
    op.create_table('calls',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('contact_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('retell_call_id', sa.String(length=128), nullable=True),
    sa.Column('call_direction', sa.String(length=20), nullable=True),
    sa.Column('agent_used', sa.String(length=255), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('patient_sentiment', sa.String(length=50), nullable=True),
    sa.Column('call_status', sa.String(length=50), nullable=True),
    sa.Column('patient_status', sa.String(length=50), nullable=True),
    sa.Column('patient_intent', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('call_date', sa.Date(), nullable=True),
    sa.Column('call_time', sa.Time(timezone=True), nullable=True),
    sa.Column('call_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('is_new_patient', sa.Boolean(), nullable=False),
    sa.Column('is_complaint', sa.Boolean(), nullable=False),
    sa.Column('is_insurance_billing', sa.Boolean(), nullable=False),
    sa.Column('preferred_callback_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('callback_resolved', sa.Boolean(), nullable=False),
    sa.Column('callback_resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('times_called', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_call_tenant', 'calls', ['tenant_id'], unique=False)
    op.create_index('ix_call_tenant_contact', 'calls', ['tenant_id', 'contact_id'], unique=False)
    op.create_index('ix_call_tenant_date', 'calls', ['tenant_id', 'call_date'], unique=False)
    op.create_index('ix_call_tenant_status', 'calls', ['tenant_id', 'call_status'], unique=False)
    op.create_index(op.f('ix_calls_call_date'), 'calls', ['call_date'], unique=False)
    op.create_index(op.f('ix_calls_call_status'), 'calls', ['call_status'], unique=False)
    op.create_index(op.f('ix_calls_contact_id'), 'calls', ['contact_id'], unique=False)
    op.create_index(op.f('ix_calls_retell_call_id'), 'calls', ['retell_call_id'], unique=True)
    op.create_index(op.f('ix_calls_tenant_id'), 'calls', ['tenant_id'], unique=False)
    op.create_table('custom_field_values',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('field_definition_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_encrypted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_definition_id'], ['custom_field_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_definition_id', 'entity_id', name='uq_custom_field_value_def_entity')
    )
    op.create_index('ix_custom_field_val_tenant_entity', 'custom_field_values', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_custom_field_values_field_definition_id'), 'custom_field_values', ['field_definition_id'], unique=False)
    op.drop_index(op.f('ix_tenant_availabilities_location_id'), table_name='tenant_availabilities')
    op.drop_index(op.f('ix_tenant_availabilities_tenant_id'), table_name='tenant_availabilities')
    op.drop_table('tenant_availabilities')
    op.drop_column('retell_webhook_events', 'ghl_contact_id')
    op.drop_column('tenant_locations', 'ghl_location_id')
    op.drop_column('tenant_locations', 'sikka_office_id')
    op.drop_column('tenants', 'ghl_api_key_encrypted')
    op.drop_column('tenants', 'ghl_custom_fields')
    op.drop_column('tenants', 'sikka_app_id_encrypted')
    op.drop_column('tenants', 'sikka_app_secret_encrypted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('sikka_app_secret_encrypted', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('sikka_app_id_encrypted', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('ghl_custom_fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('ghl_api_key_encrypted', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tenant_locations', sa.Column('sikka_office_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tenant_locations', sa.Column('ghl_location_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('retell_webhook_events', sa.Column('ghl_contact_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.create_table('tenant_availabilities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('provider_source_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('provider_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('operatory_source_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('operatory_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('begin_time', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('end_time', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('days', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('specific_date', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('appointment_type_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('appointment_type_names', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('synced', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('source_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('synced_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['tenant_locations.id'], name=op.f('tenant_availabilities_location_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('tenant_availabilities_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tenant_availabilities_pkey'))
    )
    op.create_index(op.f('ix_tenant_availabilities_tenant_id'), 'tenant_availabilities', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_availabilities_location_id'), 'tenant_availabilities', ['location_id'], unique=False)
    op.drop_index(op.f('ix_custom_field_values_field_definition_id'), table_name='custom_field_values')
    op.drop_index('ix_custom_field_val_tenant_entity', table_name='custom_field_values')
    op.drop_table('custom_field_values')
    op.drop_index(op.f('ix_calls_tenant_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_retell_call_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_contact_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_call_status'), table_name='calls')
    op.drop_index(op.f('ix_calls_call_date'), table_name='calls')
    op.drop_index('ix_call_tenant_status', table_name='calls')
    op.drop_index('ix_call_tenant_date', table_name='calls')
    op.drop_index('ix_call_tenant_contact', table_name='calls')
    op.drop_index('ix_call_tenant', table_name='calls')
    op.drop_table('calls')
    op.drop_index('ix_custom_field_def_tenant_entity', table_name='custom_field_definitions')
    op.drop_table('custom_field_definitions')
    op.drop_index(op.f('ix_contacts_tenant_id'), table_name='contacts')
    op.drop_index('ix_contact_tenant_nexhealth', table_name='contacts')
    op.drop_index('ix_contact_tenant', table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
