"""add_sms_history_logs

Revision ID: c9e76b8323c7
Revises: 20260305_add_location_hours_breaks
Create Date: 2026-03-05 17:04:47.977093+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e76b8323c7'
down_revision: Union[str, None] = '20260305_add_location_hours_breaks'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_history_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('from_number', sa.String(length=50), nullable=False),
    sa.Column('to_number_encrypted', sa.Text(), nullable=False),
    sa.Column('body_encrypted', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message_sid', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('institution_location_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_contact_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('call_id', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_location_id'], ['institution_locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_history_logs_call_id'), 'sms_history_logs', ['call_id'], unique=False)
    op.create_index(op.f('ix_sms_history_logs_institution_location_id'), 'sms_history_logs', ['institution_location_id'], unique=False)
    op.create_index(op.f('ix_sms_history_logs_patient_contact_id'), 'sms_history_logs', ['patient_contact_id'], unique=False)
    op.create_index(op.f('ix_sms_history_logs_status'), 'sms_history_logs', ['status'], unique=False)
    op.create_index(op.f('ix_sms_history_logs_timestamp'), 'sms_history_logs', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_calls_tenant_id'), table_name='calls')
    op.create_index(op.f('ix_calls_institution_id'), 'calls', ['institution_id'], unique=False)
    op.drop_index(op.f('ix_contacts_tenant_id'), table_name='contacts')
    op.create_index(op.f('ix_contacts_institution_id'), 'contacts', ['institution_id'], unique=False)
    op.drop_index(op.f('ix_tenant_appointment_types_location_id'), table_name='institution_appointment_types')
    op.create_index(op.f('ix_institution_appointment_types_location_id'), 'institution_appointment_types', ['location_id'], unique=False)
    op.drop_index(op.f('ix_tenant_descriptors_location_id'), table_name='institution_descriptors')
    op.create_index(op.f('ix_institution_descriptors_location_id'), 'institution_descriptors', ['location_id'], unique=False)
    op.drop_index(op.f('ix_tenant_locations_retell_agent_id'), table_name='institution_locations')
    op.drop_index(op.f('ix_tenant_locations_slug'), table_name='institution_locations')
    op.create_index(op.f('ix_institution_locations_retell_agent_id'), 'institution_locations', ['retell_agent_id'], unique=False)
    op.create_index(op.f('ix_institution_locations_slug'), 'institution_locations', ['slug'], unique=True)
    op.drop_index(op.f('ix_tenant_operatories_location_id'), table_name='institution_operatories')
    op.create_index(op.f('ix_institution_operatories_location_id'), 'institution_operatories', ['location_id'], unique=False)
    op.drop_index(op.f('ix_tenant_providers_location_id'), table_name='institution_providers')
    op.create_index(op.f('ix_institution_providers_location_id'), 'institution_providers', ['location_id'], unique=False)
    op.drop_index(op.f('ix_tenants_slug'), table_name='institutions')
    op.create_index(op.f('ix_institutions_slug'), 'institutions', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institutions_slug'), table_name='institutions')
    op.create_index(op.f('ix_tenants_slug'), 'institutions', ['slug'], unique=True)
    op.drop_index(op.f('ix_institution_providers_location_id'), table_name='institution_providers')
    op.create_index(op.f('ix_tenant_providers_location_id'), 'institution_providers', ['location_id'], unique=False)
    op.drop_index(op.f('ix_institution_operatories_location_id'), table_name='institution_operatories')
    op.create_index(op.f('ix_tenant_operatories_location_id'), 'institution_operatories', ['location_id'], unique=False)
    op.drop_index(op.f('ix_institution_locations_slug'), table_name='institution_locations')
    op.drop_index(op.f('ix_institution_locations_retell_agent_id'), table_name='institution_locations')
    op.create_index(op.f('ix_tenant_locations_slug'), 'institution_locations', ['slug'], unique=True)
    op.create_index(op.f('ix_tenant_locations_retell_agent_id'), 'institution_locations', ['retell_agent_id'], unique=False)
    op.drop_index(op.f('ix_institution_descriptors_location_id'), table_name='institution_descriptors')
    op.create_index(op.f('ix_tenant_descriptors_location_id'), 'institution_descriptors', ['location_id'], unique=False)
    op.drop_index(op.f('ix_institution_appointment_types_location_id'), table_name='institution_appointment_types')
    op.create_index(op.f('ix_tenant_appointment_types_location_id'), 'institution_appointment_types', ['location_id'], unique=False)
    op.drop_index(op.f('ix_contacts_institution_id'), table_name='contacts')
    op.create_index(op.f('ix_contacts_tenant_id'), 'contacts', ['institution_id'], unique=False)
    op.drop_index(op.f('ix_calls_institution_id'), table_name='calls')
    op.create_index(op.f('ix_calls_tenant_id'), 'calls', ['institution_id'], unique=False)
    op.drop_index(op.f('ix_sms_history_logs_timestamp'), table_name='sms_history_logs')
    op.drop_index(op.f('ix_sms_history_logs_status'), table_name='sms_history_logs')
    op.drop_index(op.f('ix_sms_history_logs_patient_contact_id'), table_name='sms_history_logs')
    op.drop_index(op.f('ix_sms_history_logs_institution_location_id'), table_name='sms_history_logs')
    op.drop_index(op.f('ix_sms_history_logs_call_id'), table_name='sms_history_logs')
    op.drop_table('sms_history_logs')
    # ### end Alembic commands ###
