"""refactor_tenant_mapping

Revision ID: 02020a12359a
Revises: 20260219_0004
Create Date: 2026-02-20 04:14:41.936330+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02020a12359a'
down_revision: Union[str, None] = '20260219_0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_locations', sa.Column('ghl_location_id', sa.String(length=100), nullable=True))
    op.add_column('tenant_locations', sa.Column('sikka_office_id', sa.String(length=100), nullable=True))
    op.drop_index(op.f('ix_tenants_retell_agent_id'), table_name='tenants')
    op.drop_column('tenants', 'retell_agent_id')
    op.drop_column('tenants', 'nexhealth_location_id')
    op.drop_column('tenants', 'ghl_location_id')
    op.drop_column('tenants', 'sikka_office_id')
    op.drop_column('tenants', 'nexhealth_subdomain')
    op.drop_index(op.f('ix_users_supabase_id'), table_name='users')
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.drop_column('users', 'supabase_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('supabase_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.create_index(op.f('ix_users_supabase_id'), 'users', ['supabase_id'], unique=False)
    op.add_column('tenants', sa.Column('nexhealth_subdomain', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('sikka_office_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('ghl_location_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('nexhealth_location_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('retell_agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_tenants_retell_agent_id'), 'tenants', ['retell_agent_id'], unique=False)
    op.drop_column('tenant_locations', 'sikka_office_id')
    op.drop_column('tenant_locations', 'ghl_location_id')
    # ### end Alembic commands ###
