// @ui-variant classic — delete this file to drop the classic UI.
//
// The line icons the sidebar used before illustrated artwork replaced
// them. The nav was refactored to key artwork off the route and dropped
// its per-item icons entirely, so without this classic mode would render
// a nav with no icons at all.
import {
    Armchair,
    Building2,
    CalendarCheck,
    CalendarClock,
    CalendarOff,
    ClipboardList,
    FormInput as FormInputIcon,
    Home,
    Inbox as InboxIcon,
    Layers,
    LayoutDashboard,
    Mail,
    MailCheck,
    Megaphone,
    MessageSquare,
    Phone,
    PhoneForwarded,
    Settings,
    Shield,
    ShieldCheck,
    ShieldOff,
    Tag,
    TriangleAlert,
    UserCog,
    Users,
} from "lucide-react"
import type { LucideIcon } from "lucide-react"

export const NAV_GLYPH: Record<string, LucideIcon> = {
    "/admin": LayoutDashboard,
    "/admin/audit-logs": ShieldCheck,
    "/admin/twilio": MessageSquare,
    "/admin/users": UserCog,
    "/callbacks": PhoneForwarded,
    "/calls": Phone,
    "/contacts": Users,
    "/dashboard": Home,
    "/group": Layers,
    "/groups": Layers,
    "/inbox": InboxIcon,
    "/institution-admin": Building2,
    "/institution-admin/appointment-sync": CalendarClock,
    "/institution-admin/call-statuses": Tag,
    "/institution-admin/campaigns": Megaphone,
    "/institution-admin/do-not-contact": ShieldOff,
    "/institution-admin/email-inbox": InboxIcon,
    "/institution-admin/email-sending-address": MailCheck,
    "/institution-admin/email-templates": Mail,
    "/institution-admin/lead-forms": FormInputIcon,
    "/institution-admin/quiet-hours-exceptions": CalendarOff,
    "/institution-admin/settings": Settings,
    "/institution-admin/sms-templates": MessageSquare,
    "/institution-admin/users": Users,
    "/institutions": Users,
    "/location-admin": Building2,
    "/notification-preferences": MailCheck,
    "/patients": ClipboardList,
    "/setup": ClipboardList,
    "/setup/appointment-types": CalendarCheck,
    "/setup/audit-logs": ShieldCheck,
    "/setup/insurance-plans": Shield,
    "/setup/operatories": Armchair,
    "/setup/providers": UserCog,
    "/setup/reasons": Tag,
    "/sms-preferences": MessageSquare,
    "/undeliverables": TriangleAlert,
}
