"""Tenant-scope invariant — every PHI-table query must filter by institution_id.

This test is the cheap defense-in-depth alternative to PostgreSQL Row-Level
Security: it walks the source tree, finds every ``select(Model)`` against a
PHI-bearing model, and asserts the query has an ``institution_id`` predicate
in its WHERE clause.

Add a finding to ``ALLOWLIST`` only when a cross-tenant query is genuinely
intentional (e.g. a platform-admin diagnostic). Each entry needs a comment
explaining *why* it's safe.

If RLS is restored later, this test stays useful as a static-analysis
catch-all that runs in milliseconds against every PR.
"""

from __future__ import annotations

import re
from pathlib import Path

# PHI-bearing models. Adding a row to this set is a security upgrade — every
# new finding will surface here so it can be reviewed.
PHI_MODELS = frozenset({
    "Call",
    "Contact",
    "AuditLog",
    "SmsHistoryLog",
    "Notification",
    "ConsentRecord",
    "DoNotContact",
    "SmsSuppression",
    "CustomFieldValue",
    "RetellWebhookEvent",
    "RetellFunctionInvocation",
    "DeadLetterEvent",
})


# (relative_path, line_number, model) — queries verified to be safe-by-design.
# Add a one-line justification for each entry. Update line numbers when files
# change.
ALLOWLIST: set[tuple[str, int, str]] = {
    # Retell idempotency tables are keyed by (call_id, ...). The call_id is
    # generated by Retell and is globally unique across the platform; the
    # institution association is recorded on the row only after the handler
    # resolves it. A cross-tenant collision would require two clinics to
    # share the same Retell call_id, which Retell guarantees never happens.
    ("src/app/retell/idempotency.py", 96, "RetellFunctionInvocation"),
    ("src/app/retell/idempotency.py", 182, "RetellFunctionInvocation"),
    ("src/app/retell/webhooks.py", 150, "RetellWebhookEvent"),
    ("src/app/retell/webhooks.py", 212, "RetellWebhookEvent"),

    # Twilio status callback identifies our row by message_sid (Twilio's
    # globally unique message id). Twilio doesn't know our institution_id.
    # Adding institution_id would require Twilio to send it back, which
    # they won't.
    ("src/app/services/sms_service.py", 291, "SmsHistoryLog"),

    # The scheduled retention job is an admin task that runs once per day
    # with DATABASE_ADMIN_URL and intentionally scans expired records across
    # tenants. It only clears PHI whose retention deadline has passed and
    # skips rows under legal hold.
    ("src/app/services/retention_policy.py", 282, "Call"),    # expired recordings
    ("src/app/services/retention_policy.py", 331, "Call"),    # purged-call CFV cleanup
    ("src/app/services/retention_policy.py", 356, "Call"),    # retained-call EXISTS
    ("src/app/services/retention_policy.py", 390, "Contact"), # anonymized-contact CFV

    # Contact-detail (Patients page) loads a primary contact's aliases and the
    # union of their calls AFTER the primary has been institution-scoped by
    # ``_scoped_contact`` (checks institution_id + location access). The alias
    # query keys on ``merged_into_id == contact.id`` and the calls query on
    # ``contact_id IN <member ids>`` — both derived from that scoped contact,
    # and RLS enforces institution_id on Contact and Call regardless.
    ("src/app/api/routes/contacts.py", 293, "Contact"),  # aliases of scoped primary
    ("src/app/api/routes/contacts.py", 304, "Call"),     # calls of scoped primary + aliases
}


SRC_ROOT = Path(__file__).resolve().parents[2] / "src" / "app"


_SELECT_RE = re.compile(r"\bselect\(\s*(\w+)\b")


def _query_block(text: str, start: int) -> str:
    """Return a window covering the select call AND its enclosing function.

    Captures up to 60 lines BEFORE the select (to catch the common pattern
    where ``conditions = [Model.institution_id == ...]`` is built ahead of
    ``select(Model).where(*conditions)``) and walks forward through chained
    method calls until the statement balances closed.
    """
    # Backward window: up to 60 lines.
    pre_start = start
    line_count = 0
    while pre_start > 0 and line_count < 60:
        pre_start -= 1
        if text[pre_start] == "\n":
            line_count += 1

    # Forward: balance parens through chain.
    depth = 0
    i = start
    while i < len(text):
        ch = text[i]
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                j = i + 1
                while j < len(text) and text[j] in " \t\r\n":
                    j += 1
                if j < len(text) and text[j] == ".":
                    i = j
                    continue
                return text[pre_start : i + 1]
        i += 1
    return text[pre_start : start + 2000]


def test_phi_queries_filter_by_institution_id() -> None:
    failures: list[str] = []
    files_scanned = 0
    queries_scanned = 0

    for path in sorted(SRC_ROOT.rglob("*.py")):
        if "/__pycache__/" in str(path):
            continue
        files_scanned += 1
        rel = path.relative_to(SRC_ROOT.parent.parent).as_posix()
        text = path.read_text(encoding="utf-8")

        for match in _SELECT_RE.finditer(text):
            model = match.group(1)
            if model not in PHI_MODELS:
                continue
            queries_scanned += 1
            line_no = text[: match.start()].count("\n") + 1
            if (rel, line_no, model) in ALLOWLIST:
                continue

            block = _query_block(text, match.start())
            if "institution_id" in block:
                continue

            failures.append(
                f"{rel}:{line_no}  select({model}) has no institution_id "
                "predicate. Add ``Model.institution_id == <scope>`` to the "
                f"WHERE clause, or allowlist (rel='{rel}', line={line_no}, "
                f"model='{model}') with a justification."
            )

    assert files_scanned > 50, (
        f"Scanned only {files_scanned} files — path resolution likely broken"
    )
    assert queries_scanned > 0, "Found no PHI queries — regex likely broken"
    assert not failures, (
        "Tenant-scope invariant violated:\n  " + "\n  ".join(failures)
    )
